name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
    - name: Clone source code
      env:
        KERNEL: 4.4 #3.4|4.4
      run: |
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
        else
        git clone --depth=1 https://github.com/hongdou9022/rt-n56u.git /opt/rt-n56u
        fi
        cd /opt/rt-n56u/toolchain-mipsel
        sudo ./dl_toolchain.sh
        sudo mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: K2P_nano
        KERNEL: 4.4 #3.4|4.4
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        sudo cp -f configs/templates/$TNAME.config .config
        ###########
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_HTTPS=n/CONFIG_FIRMWARE_INCLUDE_HTTPS=y/g' .config
        ###########
        if [ $KERNEL = "4.4" ] ; then
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_TTYD=n/CONFIG_FIRMWARE_INCLUDE_TTYD=y/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_IPERF3=n/CONFIG_FIRMWARE_INCLUDE_IPERF3=y/g' .config
        # echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config
        # echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
        fi
        ###########
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
